version: "3.9"

services:
  devbox:
    image: africanfuture/devbox:latest
    container_name: devbox
    privileged: true
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
    working_dir: /workspace
    volumes:
      - devbox-data:/home/devuser
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"   # Next.js or frontend
      - "8000:8000"   # Backend/Dev server
      - "5432:5432"   # PostgreSQL
      - "3306:3306"   # MySQL
      - "6379:6379"   # Redis
      - "27017:27017" # MongoDB

volumes:
  devbox-data: