version: '3.9'

services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: africanfuture/devbox:latest
    container_name: devbox
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true
    runtime: nvidia  # Enable GPU if supported