name: Build and Push MSYS2 Base Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (Linux)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.linux
          push: true
          tags: |
            africanfuture/msys2-base:linux
            africanfuture/msys2-base:linux-latest
          platforms: linux/amd64

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]
            [worker.oci]
              enabled = false
            [worker.containerd]
              enabled = true
              snapshotter = "windows"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (Windows)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.windows
          push: true
          tags: |
            africanfuture/msys2-base:windows
            africanfuture/msys2-base:windows-latest
          platforms: windows/amd64

      - name: Capture build output (Windows)
        if: failure()
        run: |
          $buildOutput = docker build -f Dockerfile.windows -t africanfuture/msys2-base:windows . 2>&1
          $buildOutput | Out-File -FilePath build.log
          Get-Content build.log
        shell: powershell