build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image (Windows)
        run: |
          $env:DOCKER_BUILDKIT = "0"
          docker build --isolation=process -f Dockerfile.windows -t africanfuture/msys2-base:windows .
        shell: powershell

      - name: Push image (Windows)
        run: |
          docker tag africanfuture/msys2-base:windows africanfuture/msys2-base:windows-latest
          docker push africanfuture/msys2-base:windows
          docker push africanfuture/msys2-base:windows-latest
        shell: powershell