name: Build and Push MSYS2 Base Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (Linux)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.linux
          push: true
          tags: |
            africanfuture/msys2-base:linux
            africanfuture/msys2-base:linux-latest

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (Windows)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.windows
          push: true
          tags: |
            africanfuture/msys2-base:windows
            africanfuture/msys2-base:windows-latest

      - name: Capture build output (Windows)
        if: failure()
        run: |
          # Redirect build output to a log file during the build step (if needed)
          # Note: docker/build-push-action doesn't output to a file by default, so this is a fallback
          $buildOutput = docker build -f Dockerfile.windows -t africanfuture/msys2-base:windows . 2>&1
          $buildOutput | Out-File -FilePath build.log
          Get-Content build.log
        shell: powershell