version: '3.9'

services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: msys2-devbox
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true